from sopel import module

import random
import re


def configure(config):
    pass


def setup(bot):
    pass

# sigh, this really has to be a thing?
WORDS_BLACKLIST = [
    "nigger", "n1gger", "n1gg3r", "nigg3r"
]


@module.commands('hueg', 'h')
@module.example('.hueg BIG COLORFUL TEXT')
@module.require_privilege(module.VOICE, 'nope')
@module.rate(user=30, channel=10)
def hueg_text(bot, trigger):
    """Sends BIG \x0304C\x0307O\x0308L\x0309O\x0311R\x0310F\x0312U\x0302L\x03 TEXT"""
    
    blacklist = [
        "dumbguy",
        "snitch", "iamasnitch", "imasnitch",
        "plusme",
        "insect-", "insect--", "insect---",
        "rat", "rat-", "rat--", "rat---", "rat----", "rat-----", "rat------",
        "spick", "spick-", "spick--", "spick---", "spick----", "spick-----", "spick------",
    ]
    # print(trigger.hostmask)
    for bl in blacklist:
        if bl in trigger.hostmask:
            return
    if "snitch" in trigger.nick.lower():
        return
    if trigger.nick.lower() in blacklist:
        return

    # check for messageut
    message = trigger.group(2)
    if not message: return bot.reply("I need something to make hueg")

    check = message.strip().lower()
    check = "".join(check.split())
    if check in WORDS_BLACKLIST:
        return bot.reply(":|")
    for word in WORDS_BLACKLIST:
        if word in check:
            return bot.reply(":|")

    # parse messageut & assign colors
    message = _strip(message)
    colors = _color_picker(max_value=99) # can send max/min_value=0-99 to alter choice range
    parsed_message = _parse(message) # max_chars=10
    if len(parsed_message) > 3:
        return bot.reply("Sorry, that message is too long")
    processed_message = _process(parsed_message, colors) # scale=1

    # reply
    for line in processed_message:
        bot.write(['PRIVMSG', trigger.sender], line)


def _strip(message):
    return ''.join(char for char in message if ord(char) < 128)


def _color_picker(min_value=2, max_value=15):
    # Blocked colors
    fg_blocked_colors = [
        0,1,
        88,89,98,99,
    ]
    fg_blocked_colors.extend(range(16,52))
    bg_blocked_colors = [
        0,1,
        88,89,98,99,
    ]
    bg_blocked_colors.extend(range(52,88))
    # pick some random colors and make sure they aren't similar or the same
    random_color1 = random_color2 = 0
    while random_color1 in fg_blocked_colors:
        random_color1 = random.randint(min_value, max_value)
    random_color2 = random_color1
    while random_color2 == random_color1 or random_color2 in bg_blocked_colors \
    or abs(random_color2 - random_color1) <= 2 \
    or 12 <= abs(random_color2 - random_color1) <= 13:
        random_color2 = random.randint(min_value, max_value)
    # zero pad and assign/return
    random_color1 = str(random_color1).rjust(2, '0')
    random_color2 = str(random_color2).rjust(2, '0')
    return [
        "\x03{choice},{choice}".format(choice=random_color2),
        "\x03{choice},{choice}".format(choice=random_color1),
        "\x03"]


def _parse(message, max_chars=10):
    # split long strings
    message = re.sub(r"(\S{%s})" % max_chars, "\\1 ", message, 0)
    split_strings = message.split()
    strings_list = [""]
    counter = 0
    for word in split_strings:
        word_length = len(word)
        try:
            string_length = len(strings_list[counter]) + word_length
        except:
            string_length = 0
        if string_length <= max_chars:
            strings_list[counter] += "{} ".format(word)
        else:
            counter += 1
            strings_list.append("{} ".format(word))

    return strings_list


def _process(messages, colors, scale=1):
    lines = []
    color_map = {
        "color1": colors[0],
        "color2": colors[1],
        "color3": colors[2]
    }
    for text in messages:
        line = list(text.strip())
        current_string = ""
        for block in range(9*scale):
            block_line = ""
            for letter in line:
                block_line += "{color3} \x03".format(**color_map)
                hueg_char = HUEG_CHAR_DB.get(letter)
                if not hueg_char: continue
                current_string = f"{hueg_char[int(block/scale)].format(**color_map)}"
                whitespace = " " * scale
                current_string = re.sub(r" ", whitespace, current_string, 0)
                block_line += current_string
            block_line += "{color3} ".format(**color_map)
            lines.append(block_line)
    return lines


#------------------#
#   character db   #
#       lol        #
#------------------#

HUEG_CHAR_DB = {
    " ": [
        "{color3}      ",
        "{color3}      ",
        "{color3}      ",
        "{color3}      ",
        "{color3}      ",
        "{color3}      ",
        "{color3}      ",
        "{color3}      ",
        "{color3}      ",
    ],
    "\cC": [
        "{color3}             ",
        "{color1} {color2}  {color3}  {color1} {color2}       {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}     ",
        "{color1} {color2}            {color3}",
        "{color3}     {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}     {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}       {color3}  {color1} {color2}  {color3}",
        "{color3}             ",
    ],
    "\cB": [
        "{color3}             ",
        "{color1} {color2}  {color3}  {color1} {color2}       {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}     ",
        "{color1} {color2}            {color3}",
        "{color3}     {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}     {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}       {color3}  {color1} {color2}  {color3}",
        "{color3}             ",
    ],
    "\cO": [
        "{color3}             ",
        "{color1} {color2}  {color3}  {color1} {color2}       {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}     ",
        "{color1} {color2}            {color3}",
        "{color3}     {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}     {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}       {color3}  {color1} {color2}  {color3}",
        "{color3}             ",
    ],
    "0": [
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3} ",
        "{color3}         ",
    ],
    "1": [
        "{color3}       ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}   {color3}  ",
        "{color1} {color2}    {color3}  ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color1} {color2}      {color3}",
        "{color3}       ",
    ],
    "2": [
        "{color3}        ",
        "{color3} {color1} {color2}     {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}   {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}   ",
        "{color3} {color1} {color2}  {color3}    ",
        "{color1} {color2}       {color3}",
        "{color3}        ",
    ],
    "3": [
        "{color3}        ",
        "{color3} {color1} {color2}     {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}     {color1} {color2}  {color3}",
        "{color3}   {color1} {color2}   {color3} ",
        "{color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}     {color3} ",
        "{color3}        ",
    ],
    "4": [
        "{color3}        ",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}   {color1} {color2}   {color3} ",
        "{color3}  {color1} {color2} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2} {color3} {color1} {color2}  {color3} ",
        "{color1} {color2}       {color3}",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}        ",
    ],
    "5": [
        "{color3}        ",
        "{color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}      {color3} ",
        "{color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}     {color3} ",
        "{color3}        ",
    ],
    "6": [
        "{color3}        ",
        "{color3}   {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}   ",
        "{color3} {color1} {color2}  {color3}    ",
        "{color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}     {color3} ",
        "{color3}        ",
    ],
    "7": [
        "{color3}         ",
        "{color1} {color2}        {color3}",
        "{color3}      {color1} {color2}  {color3}",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}  {color1} {color2}  {color3}    ",
        "{color3} {color1} {color2}  {color3}     ",
        "{color3}         ",
    ],
    "8": [
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3} ",
        "{color3}         ",
    ],
    "9": [
        "{color3}        ",
        "{color3} {color1} {color2}     {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3}",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}   {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}   ",
        "{color3}        ",
    ],
    "A": [
        "{color3}        ",
        "{color3}  {color1} {color2}   {color3}  ",
        "{color3} {color1} {color2}  {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}       {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}        ",
    ],
    "a": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3} {color1} {color2}     {color3}  ",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}       {color3}",
        "{color3}         ",
    ],
    "B": [
        "{color3}         ",
        "{color1} {color2}       {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}       {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}       {color3} ",
        "{color3}         ",
    ],
    "b": [
        "{color3}         ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}      {color3}  ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3} ",
        "{color1} {color2}      {color3}  ",
        "{color3}         ",
    ],
    "C": [
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3} ",
        "{color3}         ",
    ],
    "c": [
        "{color3}        ",
        "{color3}        ",
        "{color3}        ",
        "{color3}  {color1} {color2}     {color3}",
        "{color3} {color1} {color2}  {color3}    ",
        "{color1} {color2}  {color3}     ",
        "{color3} {color1} {color2}  {color3}    ",
        "{color3}  {color1} {color2}     {color3}",
        "{color3}        ",
    ],
    "D": [
        "{color3}          ",
        "{color1} {color2}       {color3}  ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color1} {color2}       {color3}  ",
        "{color3}          ",
    ],
    "d": [
        "{color3}         ",
        "{color3}      {color1} {color2}  {color3}",
        "{color3}      {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}      {color3}",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}      {color3}",
        "{color3}         ",
    ],
    "E": [
        "{color3}        ",
        "{color1} {color2}       {color3}",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}       {color3}",
        "{color3}        ",
    ],
    "e": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  ",
        "{color1} {color2}       {color3} ",
        "{color1} {color2}  {color3}      ",
        "{color3} {color1} {color2}      {color3} ",
        "{color3}         ",
    ],
    "F": [
        "{color3}        ",
        "{color1} {color2}       ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color3}        ",
    ],
    "f": [
        "{color3}      ",
        "{color3}      ",
        "{color3}  {color1} {color2}   ",
        "{color3} {color1} {color2}  {color3}  ",
        "{color1} {color2}     ",
        "{color3} {color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}  {color3}  ",
        "{color3}      ",
    ],
    "G": [
        "{color3}          ",
        "{color3}  {color1} {color2}      {color3} ",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}       ",
        "{color1} {color2}  {color3}  {color1} {color2}    {color3}",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}      {color3} ",
        "{color3}          ",
    ],
    "g": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}       {color3}",
        "{color3}      {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3} ",
    ],
    "H": [
        "{color3}         ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}        {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3}         ",
    ],
    "h": [
        "{color3}         ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}       {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3}         ",
    ],
    "I": [
        "{color3}       ",
        "{color1} {color2}      {color3}",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color1} {color2}      {color3}",
        "{color3}       ",
    ],
    "i": [
        "{color3}     ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}     ",
        "{color1} {color2}   {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color1} {color2}    ",
        "{color3}     ",
    ],
    "J": [
        "{color3}        ",
        "{color3} {color1} {color2}      ",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}    {color3}  ",
        "{color3}        ",
    ],
    "j": [
        "{color3}       ",
        "{color3}    {color1} {color2}  ",
        "{color3}       ",
        "{color3}   {color1} {color2}   ",
        "{color3}    {color1} {color2}  ",
        "{color3}    {color1} {color2}  ",
        "{color3}    {color1} {color2}  ",
        "{color1} {color2}  {color3} {color1} {color2}  ",
        "{color3} {color1} {color2}    {color3} ",
    ],
    "K": [
        "{color3}        ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color1} {color2}  {color3}  ",
        "{color1} {color2}    {color3}   ",
        "{color1} {color2}  {color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}        ",
    ],
    "k": [
        "{color3}        ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}  {color1} {color2}  ",
        "{color1} {color2}  {color3} {color1} {color2}  {color3} ",
        "{color1} {color2}     {color3}  ",
        "{color1} {color2}  {color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  ",
        "{color3}        ",
    ],
    "L": [
        "{color3}        ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}       {color3}",
        "{color3}        ",
    ],
    "l": [
        "{color3}     ",
        "{color1} {color2}   {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color1} {color2}    ",
        "{color3}     ",
    ],
    "M": [
        "{color3}            ",
        "{color1} {color2}  {color3}      {color1} {color2}  {color3}",
        "{color1} {color2}   {color3}    {color1} {color2}   {color3}",
        "{color1} {color2}    {color3}  {color1} {color2}    {color3}",
        "{color1} {color2}  {color1} {color2}  {color1} {color2}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2}   {color3} {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2} {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}      {color1} {color2}  {color3}",
        "{color3}            ",
    ],
    "m": [
        "{color3}          ",
        "{color3}          ",
        "{color3}          ",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}  {color3} ",
        "{color1} {color2}    {color1} {color2}    {color3}",
        "{color1} {color2}  {color1} {color2}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2} {color3} {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color3}          ",
    ],
    "N": [
        "{color3}           ",
        "{color1} {color2}   {color3}    {color1} {color2}  ",
        "{color1} {color2}    {color3}   {color1} {color2}  ",
        "{color1} {color2}  {color1} {color2}  {color3}  {color1} {color2}  ",
        "{color1} {color2}  {color3} {color1} {color2}  {color3} {color1} {color2}  ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color1} {color2}  ",
        "{color1} {color2}  {color3}   {color1} {color2}    ",
        "{color1} {color2}  {color3}    {color1} {color2}   ",
        "{color3}           ",
    ],
    "n": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3}         ",
    ],
    "O": [
        "{color3}           ",
        "{color3}  {color1} {color2}      {color3}  ",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}      {color3}  ",
        "{color3}           ",
    ],
    "o": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3} ",
        "{color3}         ",
    ],
    "P": [
        "{color3}         ",
        "{color1} {color2}       {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}       {color3} ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}      ",
        "{color3}         ",
    ],
    "p": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}       {color3} ",
        "{color1} {color2}  {color3}      ",
        "{color1} {color2}  {color3}      ",
    ],
    "Q": [
        "{color3}           ",
        "{color3}  {color1} {color2}      {color3}  ",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}   {color3} ",
        "{color3}  {color1} {color2}      {color3}  ",
        "{color3}       {color1} {color2}  {color3} ",
    ],
    "q": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3} {color1} {color2}      {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}       {color3}",
        "{color3}      {color1} {color2}  {color3}",
        "{color3}      {color1} {color2}  {color3}",
    ],
    "R": [
        "{color3}           ",
        "{color1} {color2}       {color3}   ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}  ",
        "{color1} {color2}       {color3}   ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}     {color1} {color2}  ",
        "{color3}           ",
    ],
    "r": [
        "{color3}        ",
        "{color3}        ",
        "{color3}        ",
        "{color3} {color1} {color2}     {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}     ",
        "{color3}        ",
    ],
    "S": [
        "{color3}        ",
        "{color3} {color1} {color2}     {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     ",
        "{color3} {color1} {color2}     {color3} ",
        "{color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}     {color3} ",
        "{color3}        ",
    ],
    "s": [
        "{color3}       ",
        "{color3}       ",
        "{color3}       ",
        "{color3} {color1} {color2}     {color3}",
        "{color1} {color2}  {color3}    ",
        "{color3} {color1} {color2}    {color3} ",
        "{color3}    {color1} {color2}  {color3}",
        "{color1} {color2}     {color3} ",
        "{color3}       ",
    ],
    "T": [
        "{color3}         ",
        "{color1} {color2}        {color3}",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}         ",
    ],
    "t": [
        "{color3}       ",
        "{color3}       ",
        "{color3} {color1} {color2}  {color3}   ",
        "{color1} {color2}     {color3} ",
        "{color3} {color1} {color2}  {color3}   ",
        "{color3} {color1} {color2}  {color3}   ",
        "{color3} {color1} {color2}  {color1} {color2}  ",
        "{color3}  {color1} {color2}   {color3} ",
        "{color3}       ",
    ],
    "U": [
        "{color3}           ",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}      {color3}  ",
        "{color3}           ",
    ],
    "u": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}      {color3} ",
        "{color3}         ",
    ],
    "V": [
        "{color3}             ",
        "{color1} {color2} {color3}         {color1} {color2} ",
        "{color1} {color2}  {color3}       {color1} {color2}  ",
        "{color3} {color1} {color2}  {color3}     {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3}   {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3} {color1} {color2}  {color3}   ",
        "{color3}    {color1} {color2}    {color3}    ",
        "{color3}     {color1} {color2}  {color3}     ",
        "{color3}             ",
    ],
    "v": [
        "{color3}            ",
        "{color3}            ",
        "{color3}            ",
        "{color1} {color2}  {color3}      {color1} {color2}  ",
        "{color3} {color1} {color2}  {color3}    {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3}  {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color1} {color2}  {color3}   ",
        "{color3}    {color1} {color2}   {color3}    ",
        "{color3}            ",
    ],
    "W": [
        "{color3}           ",
        "{color1} {color2}  {color3}     {color1} {color2}  ",
        "{color1} {color2}  {color3}     {color1} {color2}  ",
        "{color1} {color2}  {color3}     {color1} {color2}  ",
        "{color1} {color2}  {color3} {color1} {color2}  {color3} {color1} {color2}  ",
        "{color1} {color2}  {color1} {color2}    {color1} {color2}  ",
        "{color1} {color2}    {color3} {color1} {color2}    ",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color3}           ",
    ],
    "w": [
        "{color3}          ",
        "{color3}          ",
        "{color3}          ",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2} {color3} {color1} {color2}  {color3}",
        "{color1} {color2}  {color1} {color2}   {color1} {color2}  {color3}",
        "{color1} {color2}    {color1} {color2}    {color3}",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}  {color3} ",
        "{color3}          ",
    ],
    "X": [
        "{color3}          ",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}   {color3}   ",
        "{color3}  {color1} {color2}  {color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3}",
        "{color3}          ",
    ],
    "x": [
        "{color3}        ",
        "{color3}        ",
        "{color3}        ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color1} {color2}  {color3} ",
        "{color3}   {color2}   {color3}  ",
        "{color3} {color1} {color2}  {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}        ",
    ],
    "Y": [
        "{color3}           ",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}    {color3}   ",
        "{color3}    {color1} {color2}  {color3}    ",
        "{color3}    {color1} {color2}  {color3}    ",
        "{color3}    {color1} {color2}  {color3}    ",
        "{color3}           ",
    ],
    "y": [
        "{color3}           ",
        "{color3}           ",
        "{color3}           ",
        "{color1} {color2}  {color3}     {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3}   {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}    {color3}   ",
        "{color3}    {color1} {color2}  {color3}    ",
        "{color3}   {color1} {color2}  {color3}     ",
    ],
    "Z": [
        "{color3}         ",
        "{color1} {color2}        {color3}",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}  {color1} {color2}  {color3}    ",
        "{color3} {color1} {color2}  {color3}     ",
        "{color1} {color2}        {color3}",
        "{color3}         ",
    ],
    "z": [
        "{color3}          ",
        "{color3}          ",
        "{color3}          ",
        "{color1} {color2}        {color3} ",
        "{color3}     {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3}    ",
        "{color3} {color1} {color2}  {color3}      ",
        "{color1} {color2}        {color3} ",
        "{color3}          ",
    ],
    "~": [
        "{color3}             ",
        "{color3}             ",
        "{color3}             ",
        "{color3}  {color1} {color2}    {color3}   {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3} {color1} {color2}  {color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}   {color1} {color2}    {color3}  ",
        "{color3}             ",
        "{color3}             ",
        "{color3}             ",
    ],
    "`": [
        "{color3}    ",
        "{color1} {color2}  {color3} ",
        "{color3} {color1} {color2}  ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
    ],
    "!": [
        "{color3}         ",
        "{color3}      {color1} {color2}  {color3}",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}  {color1} {color2}  {color3}    ",
        "{color3}         ",
        "{color1} {color2}  {color3}      ",
        "{color3}         ",
    ],
    "@": [
        "{color3}            ",
        "{color3}  {color1} {color2}       {color3}  ",
        "{color3} {color1} {color2}  {color3}    {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color1} {color2}  {color3}  {color1} {color2}     {color3} ",
        "{color3} {color1} {color2}  {color3}        ",
        "{color3}  {color1} {color2}       {color3}  ",
        "{color3}            ",
    ],
    "#": [
        "{color3}           ",
        "{color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}  ",
        "{color1} {color2}          ",
        "{color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}  ",
        "{color1} {color2}          ",
        "{color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}  ",
        "{color3}  {color1} {color2}  {color3} {color1} {color2}  {color3}  ",
        "{color3}           ",
    ],
    "$": [
        "{color3}    {color1} {color2} {color3}    ",
        "{color3} {color1} {color2}       {color3} ",
        "{color1} {color2}  {color3} {color1} {color2} {color3} {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2} {color3}    ",
        "{color3} {color1} {color2}       {color3} ",
        "{color3}    {color1} {color2} {color3} {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2} {color3} {color1} {color2}  {color3}",
        "{color3} {color1} {color2}       {color3} ",
        "{color3}    {color1} {color2} {color3}    ",
    ],
    "%": [
        "{color3}         ",
        "{color1} {color2}  {color3}   {color1} {color2}  ",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}  {color1} {color2}  {color3}    ",
        "{color3} {color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}   {color1} {color2}  ",
        "{color3}         ",
    ],
    "^": [
        "{color3}        ",
        "{color3}        ",
        "{color3}  {color1} {color2}   {color3}  ",
        "{color3} {color1} {color2}  {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  {color1} {color2}  {color3}",
        "{color3}        ",
        "{color3}        ",
        "{color3}        ",
        "{color3}        ",
    ],
    "&": [
        "{color3}           ",
        "{color3}  {color1} {color2}    {color3}    ",
        "{color3} {color1} {color2}  {color3} {color1} {color2}  {color3}   ",
        "{color3}  {color1} {color2}    {color3}    ",
        "{color3} {color1} {color2}  {color3} {color1} {color2}  {color3}   ",
        "{color1} {color2}  {color3}   {color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}    {color1} {color2}  {color3} ",
        "{color3} {color1} {color2}      {color1} {color2}  {color3}",
        "{color3}           ",
    ],
    "*": [
        "{color3}     ",
        "{color3}     ",
        "{color1} {color2} {color3} {color1} {color2} ",
        "{color3} {color1} {color2}  {color3} ",
        "{color1} {color2} {color3} {color1} {color2} ",
        "{color3}     ",
        "{color3}     ",
        "{color3}     ",
        "{color3}     ",
    ],
    "(": [
        "{color3}     ",
        "{color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3}",
        "{color3}     ",
    ],
    ")": [
        "{color3}     ",
        "{color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  ",
        "{color3}     ",
    ],
    "_": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color1} {color2}        {color3}",
        "{color3}         ",
    ],
    "-": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color1} {color2}        {color3}",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
    ],
    "+": [
        "{color3}         ",
        "{color3}         ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color1} {color2}        {color3}",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}         ",
        "{color3}         ",
    ],
    "=": [
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
        "{color1} {color2}        {color3}",
        "{color3}         ",
        "{color1} {color2}        {color3}",
        "{color3}         ",
        "{color3}         ",
        "{color3}         ",
    ],
    "|": [
        "{color3}   ",
        "{color1} {color2}  {color3}",
        "{color1} {color2}  {color3}",
        "{color1} {color2}  {color3}",
        "{color1} {color2}  {color3}",
        "{color1} {color2}  {color3}",
        "{color1} {color2}  {color3}",
        "{color1} {color2}  {color3}",
        "{color3}   ",
    ],
    "\\": [
        "{color3}         ",
        "{color1} {color2}  {color3}      ",
        "{color3} {color1} {color2}  {color3}     ",
        "{color3}  {color1} {color2}  {color3}    ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}    {color1} {color2}  {color3}  ",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3}      {color1} {color2}  {color3}",
        "{color3}         ",
    ],
    "[": [
        "{color3}     ",
        "{color1} {color2}    {color3}",
        "{color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}  ",
        "{color1} {color2}    {color3}",
        "{color3}     ",
    ],
    "]": [
        "{color3}     ",
        "{color1} {color2}    {color3}",
        "{color3}  {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}",
        "{color1} {color2}    {color3}",
        "{color3}     ",
    ],
    "{": [
        "{color3}     ",
        "{color3} {color1} {color2}   {color3}",
        "{color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}  {color3} ",
        "{color1} {color2}  {color3}  ",
        "{color3} {color1} {color2}   {color3}",
        "{color3}     ",
    ],
    "}": [
        "{color3}     ",
        "{color1} {color2}   {color3} ",
        "{color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3}",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2}  {color3}",
        "{color1} {color2}   {color3} ",
        "{color3}     ",
    ],
    ":": [
        "{color3}     ",
        "{color3}     ",
        "{color3}     ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}     ",
        "{color3}     ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}     ",
        "{color3}     ",
    ],
    ";": [
        "{color3}     ",
        "{color3}     ",
        "{color3}     ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}     ",
        "{color3}     ",
        "{color3} {color1} {color2}  {color3} ",
        "{color3}  {color1} {color2} {color3} ",
        "{color3}     ",
    ],
    "'": [
        "{color3}    ",
        "{color3} {color1} {color2}  ",
        "{color1} {color2}  {color3} ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
        "{color3}    ",
    ],
    "\"": [
        "{color3}       ",
        "{color1} {color2}  {color3} {color1} {color2}  {color3}",
        "{color1} {color2}  {color3} {color1} {color2}  {color3}",
        "{color3}       ",
        "{color3}       ",
        "{color3}       ",
        "{color3}       ",
        "{color3}       ",
        "{color3}       ",
    ],
    "<": [
        "{color3}       ",
        "{color3}       ",
        "{color3}    {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}    ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}    {color1} {color2}  {color3}",
        "{color3}       ",
        "{color3}       ",
    ],
    ">": [
        "{color3}       ",
        "{color3}       ",
        "{color1} {color2}  {color3}    ",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color3}    {color1} {color2}  {color3}",
        "{color3}  {color1} {color2}  {color3}  ",
        "{color1} {color2}  {color3}    ",
        "{color3}       ",
        "{color3}       ",
    ],
    "?": [
        "{color3}         ",
        "{color3}  {color1} {color2}     {color3} ",
        "{color3} {color1} {color2}  {color3}  {color1} {color2}  ",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}         ",
        "{color3} {color1} {color2}  {color3}     ",
        "{color3}         ",
    ],
    ",": [
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color1} {color2}  {color3}",
        "{color3} {color1} {color2} {color3}",
    ],
    ".": [
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color3}   ",
        "{color1} {color2}  ",
        "{color3}   ",
    ],
    "/": [
        "{color3}         ",
        "{color3}      {color1} {color2}  {color3}",
        "{color3}     {color1} {color2}  {color3} ",
        "{color3}    {color1} {color2}  {color3}  ",
        "{color3}   {color1} {color2}  {color3}   ",
        "{color3}  {color1} {color2}  {color3}    ",
        "{color3} {color1} {color2}  {color3}     ",
        "{color1} {color2}  {color3}      ",
        "{color3}         ",
    ],
}